name: Build & Test - GCC-11

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.7
      with:
        cmake-version: '3.19.x'

    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Install GCC-11
      run: |
        echo "deb http://mirrors.kernel.org/ubuntu hirsute main universe" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt install g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
    - name: Configure & Build
      run: |
        cmake . -Bbuild_gcc -G "Ninja Multi-Config"
        cmake --build build_gcc
    - name: Test
      run: 
        cmake --build build_gcc --target test
