name: Build & Test - Clang-12

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.7
      with:
        cmake-version: '3.19.x'

    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Install Clang-12
      run: |
        echo "deb http://mirrors.kernel.org/ubuntu hirsute main universe" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt install clang-12
    - name: Configure & Build
      run: |
        cmake . -Bbuild_clang -DCMAKE_C_COMPILER=$(which clang-12) -DCMAKE_CXX_COMPILER=$(which clang++-12)
        cmake --build build_clang
    - name: Test
      run:
        cmake --build build_clang --target test
